services:
  - type: web
    name: toxic-comment-classifier
    env: python
    rootDirectory: web_app
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k gthread -t 120 -b 0.0.0.0:$PORT "app:create_app()"
    autoDeploy: true
    plan: free
